// src/infrastructure/tokens/injection-tokens.ts

export const USER_REPOSITORY = "USER_REPOSITORY";
export const NAISSANCE_REPOSITORY = "NAISSANCE_REPOSITORY";
export const ADRESSE_REPOSITORY = "ADRESSE_REPOSITORY";
export const PAIEMENT_REPOSITORY = "PAIEMENT_REPOSITORY";
export const URGENCE_REPOSITORY = "URGENCE_REPOSITORY";
export const JUSTIFICATIF_REPOSITORY = "JUSTIFICATIF_REPOSITORY";
export const CONTRAT_REPOSITORY = "CONTRAT_REPOSITORY";
