export class Contrat {
  constructor(
    public readonly id: string,
    public readonly idUser: string,
    public readonly poste: string,
    public readonly typeContrat: string,
    public readonly dateDebut: Date,
    public readonly dateFin: Date,
    public readonly etablissementDeSante: string,
    public readonly serviceDeSante: string,
    public readonly salaire: string,
    public readonly matricule: string,
    public readonly fichierContratNonSignerPdf?: string,
    public readonly fichierContratSignerPdf?: string,
    public readonly createdAt?: Date,
    public readonly updatedAt?: Date
  ) {}

  public static create(
    idUser: string,
    poste: string,
    typeContrat: string,
    dateDebut: Date,
    dateFin: Date,
    etablissementDeSante: string,
    serviceDeSante: string,
    salaire: string,
    matricule: string,
    fichierContratNonSignerPdf?: string,
    fichierContratSignerPdf?: string
  ): Contrat {
    return new Contrat(
      "", // Will be generated by DB
      idUser,
      poste,
      typeContrat,
      dateDebut,
      dateFin,
      etablissementDeSante,
      serviceDeSante,
      salaire,
      matricule,
      fichierContratNonSignerPdf,
      fichierContratSignerPdf,
      new Date(),
      new Date()
    );
  }
}
